server:
  port: 63040
  servlet:
    context-path: /content
spring:
  application:
    name: content
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/xc_content?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 990911
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: dev
        group: xuecheng-project


swagger:
  title: "学成在线内容管理系统"
  description: "内容系统管理系统对课程相关信息进行管理"
  base-package: com.xuecheng.content
  enabled: true
  version: 1.0.0

