### 上传文件
POST {{gateway_host}}/media/upload/coursefile?objectName=course/203.html
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="203.html"
Content-Type: application/octet-stream

< d:/course3655378610923263588.html
