### 上传文件
POST {{gateway_host}}/media/upload/coursefile?objectName=course/test2.html
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="test.html"
Content-Type: application/octet-stream

< d:/test.html
